pipeline {
    agent any

    environment {
        IMAGE_NAME = 'deatytim/board-backend'
        IMAGE_TAG  = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker build -t $IMAGE_NAME:$IMAGE_TAG .
                        docker push $IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy to K8S') {
            steps {
                sh '''
                    kubectl apply -f k8s/backend.yml
                    kubectl rollout restart deployment/board-backend -n jdh
                '''
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}
